package main

import (
	"bytes"
	"context"
	"fmt"
	"image"
	"image/jpeg"
	"io"
	"net/http"
	"strings"

	"github.com/bwmarrin/discordgo"
)

func init() {
	commands["!qr"] = notSpammable(answerQR)
	commands["!deepfry"] = notSpammable(answerDeepFry)
}

func answerQR(ds *discordgo.Session, mc *discordgo.MessageCreate, ctx context.Context) bool {
	commandBody := strings.TrimSpace(commandPrefixRegex.ReplaceAllString(mc.Content, ""))
	if len(commandBody) > 1000 {
		ds.ChannelMessageSend(mc.ChannelID, "Error: Content too large")
		return false
	}

	qrBytes, err := GenerateQRImage(commandBody, 1)
	if err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not make the QR: "+err.Error())
		return false
	}

	_, err = ds.ChannelMessageSendComplex(mc.ChannelID, &discordgo.MessageSend{
		Content: fmt.Sprintf("QR generated by %s", mc.Author.Mention()),
		Files: []*discordgo.File{
			{
				ContentType: "text/plain",
				Name:        "jarvbot_qr.gif",
				Reader:      bytes.NewReader(qrBytes),
			},
		},
	})
	return err == nil
}

type deepFryQueryInput struct {
	Noise      float64 `short:"n" long:"noise" default:"20" description:"Amount of image noise"`
	Saturation float64 `short:"s" long:"saturation" default:"1.7" description:"Saturation multiplier"`
	Quality    int     `short:"q" long:"quality" default:"30" description:"JPEG quality, 1-100"`
	Iterations int     `short:"i" long:"iterations" default:"2" description:"Number of JPEG compression iterations"`
}

type validatedDeepFryInput struct {
	Noise      float64
	Saturation float64
	Quality    int
	Iterations int
}

func parseAndValidateDeepFryInput(mc *discordgo.MessageCreate) (*validatedDeepFryInput, string) {
	var input deepFryQueryInput
	if err := parseCommandArgs(&input, mc.Content); err != nil {
		return nil, err.Error()
	}

	if input.Noise < 0 {
		return nil, "Noise must be 0 or greater."
	}
	noise := min(input.Noise, 255)

	if input.Saturation < 0 {
		return nil, "Saturation must be 0 or greater."
	}
	saturation := min(input.Saturation, 10)

	if input.Quality < 1 || input.Quality > 100 {
		return nil, "JPEG quality must be between 1 and 100."
	}

	if input.Iterations < 1 {
		return nil, "Iterations must be at least 1."
	}
	iterations := min(input.Iterations, 10)

	return &validatedDeepFryInput{
		Noise:      noise,
		Saturation: saturation,
		Quality:    input.Quality,
		Iterations: iterations,
	}, ""
}

func answerDeepFry(ds *discordgo.Session, mc *discordgo.MessageCreate, ctx context.Context) bool {
	validInput, errMsg := parseAndValidateDeepFryInput(mc)
	if errMsg != "" {
		ds.ChannelMessageSend(mc.ChannelID, errMsg)
		return false
	}

	if len(mc.Attachments) == 0 {
		ds.ChannelMessageSend(mc.ChannelID, "Please attach an image to deep fry.")
		return false
	}

	attachment := mc.Attachments[0]
	resp, err := http.Get(attachment.URL)
	if err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not download the image: "+err.Error())
		return false
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		ds.ChannelMessageSend(mc.ChannelID, fmt.Sprintf("Could not download the image: HTTP %d", resp.StatusCode))
		return false
	}

	imageBytes, err := io.ReadAll(io.LimitReader(resp.Body, maxInputImageSizeBytes+1))
	if err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not download the image: "+err.Error())
		return false
	}

	if int64(len(imageBytes)) > maxInputImageSizeBytes {
		ds.ChannelMessageSend(mc.ChannelID, "That image file is too large to deep fry.")
		return false
	}

	config, _, err := image.DecodeConfig(bytes.NewReader(imageBytes))
	if err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not read the image: "+err.Error())
		return false
	}

	if config.Width*config.Height > maxInputImagePixels {
		ds.ChannelMessageSend(mc.ChannelID, "That image is too large to deep fry.")
		return false
	}

	src, _, err := image.Decode(bytes.NewReader(imageBytes))
	if err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not decode the image: "+err.Error())
		return false
	}

	friedImage, err := deepFryImage(
		src,
		validInput.Noise,
		validInput.Saturation,
		validInput.Quality,
		validInput.Iterations,
	)
	if err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not deep fry the image: "+err.Error())
		return false
	}

	var jpgBytes bytes.Buffer
	if err := jpeg.Encode(&jpgBytes, friedImage, &jpeg.Options{Quality: validInput.Quality}); err != nil {
		ds.ChannelMessageSend(mc.ChannelID, "Could not encode the image: "+err.Error())
		return false
	}

	_, err = ds.ChannelMessageSendComplex(mc.ChannelID, &discordgo.MessageSend{
		Content: fmt.Sprintf("10 liters of digital olive oil used by %s", mc.Author.Mention()),
		Files: []*discordgo.File{
			{
				ContentType: "image/jpeg",
				Name:        "deep_fried.jpg",
				Reader:      bytes.NewReader(jpgBytes.Bytes()),
			},
		},
	})

	return err == nil
}
